tests: update bad-xml2 repo for R 4.3 compatibility
With R 4.3.1 on the latest Metworx, TestInstallWithoutRollback fails
to install RCurl

  using C compiler: ‘gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0’
  base64.c: In function ‘R_base64_decode’:
  base64.c:35:6: error: ‘PROBLEM’ undeclared (first use in this function)
     35 |      PROBLEM \"decoding from base64 failed\"
        |      ^~~~~~~
  base64.c:35:6: note: each undeclared identifier is reported only once for each function it appears in
  base64.c:35:13: error: expected ‘;’ before string constant
     35 |      PROBLEM \"decoding from base64 failed\"
        |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        |             ;
  base64.c: In function ‘R_base64_encode’:
  base64.c:73:5: error: ‘PROBLEM’ undeclared (first use in this function)
     73 |     PROBLEM \"failed to encode the data\"
        |     ^~~~~~~
  base64.c:73:12: error: expected ‘;’ before string constant
     73 |     PROBLEM \"failed to encode the data\"
        |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
        |            ;

Based on targeted tests:

 * RCurl installation fails with the RCurl version used by this test
   (1.95-4.12) under R 4.3

 * RCurl installation succeeds with RCurl 1.95-4.12 under R 4.1

 * RCurl installation succeeds with the latest RCurl version
   (1.98-1.16) under both R 4.1 and R 4.3

Update the RCurl version to 1.98-1.16 with these steps:

  $ cd localrepos/bad-xml2/src/contrib
  $ curl -fSsLO https://cran.r-project.org/src/contrib/RCurl_1.98-1.16.tar.gz
  $ curl -fSsLO https://cran.r-project.org/src/contrib/Archive/xml2/xml2_1.2.2.tar.gz
  $ cd ../..
  $ Rscript -e 'tools::write_PACKAGES("src/contrib/", type = "source")'

Then revert the xml2 change because it's intentionally corrupted for
the rollback tests.