integration_tests/baseline: update repo to get digest fix for R 4.5
The build for digest 0.6.27 fails with R 4.5.1:

    raes.c:42:44: error: expected expression before ‘char’ 42 | ctx =
       (aes_context*)Calloc(sizeof(*ctx), char); | ^~~~

That's fixed in digest's 6594e3a (use API variants of Calloc / Free
..., 2024-08-15), part of the 0.6.37 release.

Get that fix by switching spots that install digest to use the latest
MPN.

baseline/pkgr.yml explicitly installs R6 and pillar.  With the latest
MPN, this brings in three fewer packages (crayon, ellipsis, and fansi)
because pillar no longer requires these three packages and vctrs no
longer requires ellipsis.  Adjust the test assertions accordingly.