test repos: update fansi to avoid Ubuntu 22.04 compilation errors
Several of the test source repos include fansi 0.4.0, and one repo
includes 0.4.1.  These fansi versions fail to compile on Ubuntu 22.04:

  read.c:226:15: warning: too many arguments for format [-Wformat-extra-args]
    226 |               \"Internal Error: invalid color without err_code; \",
        |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  read.c: In function ‘read_esc’:
  read.c:501:13: warning: too many arguments for format [-Wformat-extra-args]
    501 |             \"Internal Error: style greater than FANSI_STYLE_MAX; \",
        |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  strsplit.c: In function ‘FANSI_strsplit’:
  strsplit.c:106:15: warning: too many arguments for format [-Wformat-extra-args]
    106 |               \"%s%s\",
        |               ^~~~~~
  unhandled.c: In function ‘FANSI_unhandled_esc’:
  unhandled.c:137:13: warning: format ‘%s’ expects a matching ‘char *’ argument [-Wformat=]
    137 |         \"%s%s\",
        |            ~^
        |             |
        |             char *
  wrap.c: In function ‘drop_pre_indent’:
  wrap.c:110:7: warning: too many arguments for format [-Wformat-extra-args]
    110 |       \"Internal Error: cannot drop indent when there is none; contact \",
        |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The latest fansi (1.0.6) compiles successfully on Ubuntu 22.04 as well
as Ubuntu 20.04.  Resolve the above failures by updating these repos
to use the latest fansi version.

Steps for updating the repos (under R 4.4):

 * download fansi from
   <https://cran.r-project.org/src/contrib/fansi_1.0.6.tar.gz> and
   copy to each repo's src/contrib/

 * for localrepos/bad-xml2 (which has an intentional corruption in the
   xml2 tarball), temporarily restore a good version of xml2 from
   <https://cran.r-project.org/src/contrib/Archive/xml2/xml2_1.2.2.tar.gz>
   so that tools::write_PACKAGES doesn't error

 * In the top-level directory of each repo, call

     Rscript -e 'tools::write_PACKAGES("src/contrib/", type = "source")'

 * restore the corrupted xml2 tarball